#ifndef LEGOOBJECTFACTORY_H
#define LEGOOBJECTFACTORY_H

#include "mxobjectfactory.h"
#include "mxatomid.h"

#define FOR_LEGOOBJECTFACTORY_OBJECTS(X)  \
  X(LegoEntityPresenter)                  \
  X(LegoActorPresenter)                   \
  X(LegoWorldPresenter)                   \
  X(LegoWorld)                            \
  X(LegoModelPresenter)                   \
  X(LegoTexturePresenter)                 \
  X(LegoPhonemePresenter)                 \
  X(LegoFlcTexturePresenter)              \
  X(LegoPalettePresenter)                 \
  X(LegoPathPresenter)                    \
  X(LegoAnimPresenter)                    \
  X(LegoLoopingAnimPresenter)             \
  X(LegoLocomotionAnimPresenter)          \
  X(LegoHideAnimPresenter)                \
  X(LegoPartPresenter)                    \
  X(LegoCarBuildAnimPresenter)            \
  X(LegoActionControlPresenter)           \
  X(LegoMeterPresenter)                   \
  X(LegoLoadCacheSoundPresenter)          \
  X(Lego3DWavePresenter)                  \
  X(LegoActor)                            \
  X(LegoPathActor)                        \
  X(LegoRaceCar)                          \
  X(LegoJetski)                           \
  X(JetskiRace)                           \
  X(LegoEntity)                           \
  X(LegoCarRaceActor)                     \
  X(LegoJetskiRaceActor)                  \
  X(LegoCarBuild)                         \
  X(Infocenter)                           \
  X(LegoAnimActor)                        \
  X(MxControlPresenter)                   \
  X(RegistrationBook)                     \
  X(HistoryBook)                          \
  X(ElevatorBottom)                       \
  X(InfocenterDoor)                       \
  X(Score)                                \
  X(ScoreState)                           \
  X(Hospital)                             \
  X(Isle)                                 \
  X(Police)                               \
  X(GasStation)                           \
  X(LegoAct2)                             \
  X(Act2State)                            \
  X(CarRace)                              \
  X(LegoRaceCarBuildState)                \
  X(LegoCopterBuildState)                 \
  X(LegoDuneCarBuildState)                \
  X(LegoJetskiBuildState)                 \
  X(HospitalState)                        \
  X(InfocenterState)                      \
  X(PoliceState)                          \
  X(GasStationState)                      \
  X(SkateBoard)                           \
  X(Helicopter)                           \
  X(HelicopterState)                      \
  X(DuneBuggy)                            \
  X(Pizza)                                \
  X(PizzaMissionState)                    \
  X(Act2Actor)                            \
  X(Act2Brick)                            \
  X(Act2GenActor)                         \
  X(Act2PoliceStation)                    \
  X(Act3)                                 \
  X(Act3State)                            \
  X(Doors)                                \
  X(LegoAnimMMPresenter)                  \
  X(RaceCar)                              \
  X(Jetski)                               \
  X(Bike)                                 \
  X(Motocycle)                            \
  X(Ambulance)                            \
  X(AmbulanceMissionState)                \
  X(TowTrack)                             \
  X(TowTrackMissionState)                 \
  X(Act3Cop)                              \
  X(Act3Brickster)                        \
  X(Act3Shark)                            \
  X(BumpBouy)                             \
  X(Act3Actor)                            \
  X(JetskiRaceState)                      \
  X(CarRaceState)                         \
  X(Act1State)                            \
  X(Pizzeria)                             \
  X(PizzeriaState)                        \
  X(InfoCenterEntity)                     \
  X(HospitalEntity)                       \
  X(GasStationEntity)                     \
  X(PoliceEntity)                         \
  X(BeachHouseEntity)                     \
  X(RaceStandsEntity)                     \
  X(JukeBoxEntity)                        \
  X(RadioState)                           \
  X(CaveEntity)                           \
  X(JailEntity)                           \
  X(MxCompositeMediaPresenter)            \
  X(JukeBox)                              \
  X(JukeBoxState)                         \
  X(RaceSkel)                             \
  X(AnimState)

// VTABLE 0x100d4768
class LegoObjectFactory : public MxObjectFactory
{
public:
  LegoObjectFactory();

  // This class retains the ClassName and IsA virtual methods from MxObjectFactory.

  virtual MxCore *Create(const char *name) override; // vtable 0x14
  virtual void Delete(MxCore *) override; // vtable 0x18
private:
  MxAtomId m_idLegoEntityPresenter;
  MxAtomId m_idLegoActorPresenter;
  MxAtomId m_idLegoWorldPresenter;
  MxAtomId m_idLegoWorld;
  MxAtomId m_idLegoModelPresenter;
  MxAtomId m_idLegoTexturePresenter;
  MxAtomId m_idLegoPhonemePresenter;
  MxAtomId m_idLegoFlcTexturePresenter;
  MxAtomId m_idLegoPalettePresenter;
  MxAtomId m_idLegoPathPresenter;
  MxAtomId m_idLegoAnimPresenter;
  MxAtomId m_idLegoLoopingAnimPresenter;
  MxAtomId m_idLegoLocomotionAnimPresenter;
  MxAtomId m_idLegoHideAnimPresenter;
  MxAtomId m_idLegoPartPresenter;
  MxAtomId m_idLegoCarBuildAnimPresenter;
  MxAtomId m_idLegoActionControlPresenter;
  MxAtomId m_idLegoMeterPresenter;
  MxAtomId m_idLegoLoadCacheSoundPresenter;
  MxAtomId m_idLego3DWavePresenter;
  MxAtomId m_idLegoActor;
  MxAtomId m_idLegoPathActor;
  MxAtomId m_idLegoRaceCar;
  MxAtomId m_idLegoJetski;
  MxAtomId m_idJetskiRace;
  MxAtomId m_idLegoEntity;
  MxAtomId m_idLegoCarRaceActor;
  MxAtomId m_idLegoJetskiRaceActor;
  MxAtomId m_idLegoCarBuild;
  MxAtomId m_idInfocenter;
  MxAtomId m_idLegoAnimActor;
  MxAtomId m_idMxControlPresenter;
  MxAtomId m_idRegistrationBook;
  MxAtomId m_idHistoryBook;
  MxAtomId m_idElevatorBottom;
  MxAtomId m_idInfocenterDoor;
  MxAtomId m_idScore;
  MxAtomId m_idScoreState;
  MxAtomId m_idHospital;
  MxAtomId m_idIsle;
  MxAtomId m_idPolice;
  MxAtomId m_idGasStation;
  MxAtomId m_idLegoAct2;
  MxAtomId m_idAct2State;
  MxAtomId m_idCarRace;
  MxAtomId m_idLegoRaceCarBuildState;
  MxAtomId m_idLegoCopterBuildState;
  MxAtomId m_idLegoDuneCarBuildState;
  MxAtomId m_idLegoJetskiBuildState;
  MxAtomId m_idHospitalState;
  MxAtomId m_idInfocenterState;
  MxAtomId m_idPoliceState;
  MxAtomId m_idGasStationState;
  MxAtomId m_idSkateBoard;
  MxAtomId m_idHelicopter;
  MxAtomId m_idHelicopterState;
  MxAtomId m_idDuneBuggy;
  MxAtomId m_idPizza;
  MxAtomId m_idPizzaMissionState;
  MxAtomId m_idAct2Actor;
  MxAtomId m_idAct2Brick;
  MxAtomId m_idAct2GenActor;
  MxAtomId m_idAct2PoliceStation;
  MxAtomId m_idAct3;
  MxAtomId m_idAct3State;
  MxAtomId m_idDoors;
  MxAtomId m_idLegoAnimMMPresenter;
  MxAtomId m_idRaceCar;
  MxAtomId m_idJetski;
  MxAtomId m_idBike;
  MxAtomId m_idMotocycle;
  MxAtomId m_idAmbulance;
  MxAtomId m_idAmbulanceMissionState;
  MxAtomId m_idTowTrack;
  MxAtomId m_idTowTrackMissionState;
  MxAtomId m_idAct3Cop;
  MxAtomId m_idAct3Brickster;
  MxAtomId m_idAct3Shark;
  MxAtomId m_idBumpBouy;
  MxAtomId m_idAct3Actor;
  MxAtomId m_idJetskiRaceState;
  MxAtomId m_idCarRaceState;
  MxAtomId m_idAct1State;
  MxAtomId m_idPizzeria;
  MxAtomId m_idPizzeriaState;
  MxAtomId m_idInfoCenterEntity;
  MxAtomId m_idHospitalEntity;
  MxAtomId m_idGasStationEntity;
  MxAtomId m_idPoliceEntity;
  MxAtomId m_idBeachHouseEntity;
  MxAtomId m_idRaceStandsEntity;
  MxAtomId m_idJukeBoxEntity;
  MxAtomId m_idRadioState;
  MxAtomId m_idCaveEntity;
  MxAtomId m_idJailEntity;
  MxAtomId m_idMxCompositeMediaPresenter;
  MxAtomId m_idJukeBox;
  MxAtomId m_idJukeBoxState;
  MxAtomId m_idRaceSkel;
  MxAtomId m_idAnimState;
};

#endif // LEGOOBJECTFACTORY_H
